# RAG服务配置文件
# 请根据实际环境修改以下配置

# 向量数据库配置
vector_index_path: "D:\\rag-project\\05-rag-practice\\23-faiss_db\\graph_node\\vector_index.faiss"
node_id_to_index_path: "D:\\rag-project\\05-rag-practice\\23-faiss_db\\graph_node\\node_id_to_index.json"
embedding_model: "all-MiniLM-L6-v2"
vector_dimension: 384
search_top_k: 5

# 知识图谱服务配置
graph_depth: 1
fastapi_url: "http://localhost:8000"  # 07-graph_loader.py提供的服务地址

# DeepSeek模型配置
deepseek_api_key: "your_api_key_here"  # 请替换为实际的DeepSeek API密钥
deepseek_model: "deepseek-chat"

# FastAPI服务配置
host: "0.0.0.0"  # 监听地址，0.0.0.0表示所有接口
port: 8001  # 服务端口，确保与07-graph_loader.py的端口不同

# 日志配置
log_level: "INFO"
log_file: "rag_service.log"